Importing pandas

In [1]:
import pandas as pd

opening a local csv file

In [5]:
df=pd.read_csv('dataset\\placement.csv')

opening a csv file from an URL

In [10]:
import requests
from io import StringIO

url="https://github.com/Shashikala-11/placement-prediction-system-using-logistic-regression/blob/main/dataset"
headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
response=requests.get(url,headers=headers)
data=StringIO(response.text)
raw_url = "https://raw.githubusercontent.com/Shashikala-11/placement-prediction-system-using-logistic-regression/main/dataset/placement.csv"
df = pd.read_csv(raw_url)
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

Sep parameter

In [12]:
df2=pd.read_csv('dataset\\iris.tsv')
df2

        5.1\t3.5\t1.4\t0.2\tSetosa
0         4.9\t3\t1.4\t0.2\tSetosa
1       4.7\t3.2\t1.3\t0.2\tSetosa
2       4.6\t3.1\t1.5\t0.2\tSetosa
3         5\t3.6\t1.4\t0.2\tSetosa
4       5.4\t3.9\t1.7\t0.4\tSetosa
..                             ...
144    6.7\t3\t5.2\t2.3\tVirginica
145    6.3\t2.5\t5\t1.9\tVirginica
146      6.5\t3\t5.2\t2\tVirginica
147  6.2\t3.4\t5.4\t2.3\tVirginica
148    5.9\t3\t5.1\t1.8\tVirginica

[149 rows x 1 columns]

In [14]:
df2=pd.read_csv('dataset\\iris.tsv',sep='\t')
df2

     5.1  3.5  1.4  0.2     Setosa
0    4.9  3.0  1.4  0.2     Setosa
1    4.7  3.2  1.3  0.2     Setosa
2    4.6  3.1  1.5  0.2     Setosa
3    5.0  3.6  1.4  0.2     Setosa
4    5.4  3.9  1.7  0.4     Setosa
..   ...  ...  ...  ...        ...
144  6.7  3.0  5.2  2.3  Virginica
145  6.3  2.5  5.0  1.9  Virginica
146  6.5  3.0  5.2  2.0  Virginica
147  6.2  3.4  5.4  2.3  Virginica
148  5.9  3.0  5.1  1.8  Virginica

[149 rows x 5 columns]

index_col parameter

In [16]:
pd.read_csv('dataset\\placement.csv',sep=',',index_col='Unnamed: 0')

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

use_cols parameter

In [17]:
pd.read_csv('dataset\\placement.csv',sep=',',usecols=['cgpa','iq'])

    cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]

skiprows parameter

In [18]:
pd.read_csv('dataset\\placement.csv',sep=',',skiprows=[i for i in range(0,100,2)])

     0  6.8  123.0  1
0    2  5.3  121.0  0
1    4  5.8  142.0  0
2    6  5.7  143.0  0
3    8  6.1  156.0  0
4   10  6.0   45.0  1
5   12  5.4  139.0  0
6   14  6.1  103.0  0
7   16  5.2  224.0  0
8   18  4.0  100.0  0
9   20  6.6  120.0  1
10  22  4.9  120.0  0
11  24  4.7  121.0  0
12  26  7.0  199.0  1
13  28  5.2   90.0  0
14  30  7.6  128.0  1
15  32  7.0  139.0  1
16  34  4.8  163.0  0
17  36  5.7  140.0  0
18  38  6.5  160.0  1
19  40  4.9  134.0  0
20  42  7.6   89.0  1
21  44  7.5   61.0  1
22  46  5.3  114.0  0
23  48  6.6  138.0  1
24  50  3.5  233.0  0
25  52  7.0  175.0  1
26  54  6.4  141.0  1
27  56  6.1   65.0  0
28  58  8.0   79.0  1
29  60  6.9  139.0  1
30  62  6.0  102.0  0
31  64  7.0   64.0  1
32  66  6.9   96.0  1
33  68  4.0   75.0  0
34  70  6.3  127.0  1
35  72  7.3  116.0  1
36  74  6.7  154.0  1
37  76  4.9  155.0  0
38  78  6.1   81.0  0
39  80  4.9  196.0  0
40  82  6.5   37.0  1
41  84  5.7  169.0  0
42  86  5.1  128.0  0
43  88  4.4  149.0  0
44  90  7.3   86.0  1
45  92  5.2  110.0  0
46  94  4.7   52.0  0
47  96  4.4   42.0  0
48  98  6.3  103.0  1
49  99  6.2  113.0  1

skip bad lines

In [ ]:
# pd.read_csv('dataset\\placement.csv',sep=',',error_bad_lines=False) 
# we can use this to skip the bad lines in the csv file. But it is deprecated in pandas 1.3.0 and later versions. So we can use the following code to skip the bad lines in the csv file.

dtypes parameter

In [28]:
df2=pd.read_csv('dataset\\iris.tsv',sep='\t')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   5.1     149 non-null    float64
 1   3.5     149 non-null    float64
 2   1.4     149 non-null    float64
 3   0.2     149 non-null    float64
 4   Setosa  149 non-null    object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [31]:
df2=pd.read_csv('dataset\\iris.tsv',sep='\t',dtype={5.1:int})
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   5.1     149 non-null    float64
 1   3.5     149 non-null    float64
 2   1.4     149 non-null    float64
 3   0.2     149 non-null    float64
 4   Setosa  149 non-null    object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [32]:
df2

     5.1  3.5  1.4  0.2     Setosa
0    4.9  3.0  1.4  0.2     Setosa
1    4.7  3.2  1.3  0.2     Setosa
2    4.6  3.1  1.5  0.2     Setosa
3    5.0  3.6  1.4  0.2     Setosa
4    5.4  3.9  1.7  0.4     Setosa
..   ...  ...  ...  ...        ...
144  6.7  3.0  5.2  2.3  Virginica
145  6.3  2.5  5.0  1.9  Virginica
146  6.5  3.0  5.2  2.0  Virginica
147  6.2  3.4  5.4  2.3  Virginica
148  5.9  3.0  5.1  1.8  Virginica

[149 rows x 5 columns]

Converters

In [33]:
def rename(name):
    if name=="Setosa":
        return 'S'
    elif name=="Virginica":
        return 'V'
    else:
        return name

In [34]:
rename('Setosa')

'S'

In [35]:
pd.read_csv('dataset\\iris.tsv',sep='\t',converters={'Setosa':rename,'Virginica':rename})

     5.1  3.5  1.4  0.2 Setosa
0    4.9  3.0  1.4  0.2      S
1    4.7  3.2  1.3  0.2      S
2    4.6  3.1  1.5  0.2      S
3    5.0  3.6  1.4  0.2      S
4    5.4  3.9  1.7  0.4      S
..   ...  ...  ...  ...    ...
144  6.7  3.0  5.2  2.3      V
145  6.3  2.5  5.0  1.9      V
146  6.5  3.0  5.2  2.0      V
147  6.2  3.4  5.4  2.3      V
148  5.9  3.0  5.1  1.8      V

[149 rows x 5 columns]

loading a huge dataset in chunks

In [36]:
dfs=pd.read_csv('dataset\\placement.csv',chunksize=10)
for chunk in dfs:
    print(chunk)

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0
5           5   7.1   48.0          1
6           6   5.7  143.0          0
7           7   5.0   63.0          0
8           8   6.1  156.0          0
9           9   5.1   66.0          0
    Unnamed: 0  cgpa     iq  placement
10          10   6.0   45.0          1
11          11   6.9  138.0          1
12          12   5.4  139.0          0
13          13   6.4  116.0          1
14          14   6.1  103.0          0
15          15   5.1  176.0          0
16          16   5.2  224.0          0
17          17   3.3  183.0          0
18          18   4.0  100.0          0
19          19   5.2  132.0          0
    Unnamed: 0  cgpa     iq  placement
20          20   6.6  120.0          1
21          21   7.1  151.0          1
22          22   4.9  120.0          0
23          23   4.7   87.0          0
24          24   4.7  121.0          0
25          25   5.0   91.0          0
26          26   7.0  199.0          1
27          27   6.0  124.0          1
28          28   5.2   90.0          0
29          29   7.0  112.0          1
    Unnamed: 0  cgpa     iq  placement
30          30   7.6  128.0          1
31          31   3.9  109.0          0
32          32   7.0  139.0          1
33          33   6.0  149.0          0
34          34   4.8  163.0          0
35          35   6.8   90.0          1
36          36   5.7  140.0          0
37          37   8.1  149.0          1
38          38   6.5  160.0          1
39          39   4.6  146.0          0
    Unnamed: 0  cgpa     iq  placement
40          40   4.9  134.0          0
41          41   5.4  114.0          0
42          42   7.6   89.0          1
43          43   6.8  141.0          1
44          44   7.5   61.0          1
45          45   6.0   66.0          1
46          46   5.3  114.0          0
47          47   5.2  161.0          0
48          48   6.6  138.0          1
49          49   5.4  135.0          0
    Unnamed: 0  cgpa     iq  placement
50          50   3.5  233.0          0
51          51   4.8  141.0          0
52          52   7.0  175.0          1
53          53   8.3  168.0          1
54          54   6.4  141.0          1
55          55   7.8  114.0          1
56          56   6.1   65.0          0
57          57   6.5  130.0          1
58          58   8.0   79.0          1
59          59   4.8  112.0          0
    Unnamed: 0  cgpa     iq  placement
60          60   6.9  139.0          1
61          61   7.3  137.0          1
62          62   6.0  102.0          0
63          63   6.3  128.0          1
64          64   7.0   64.0          1
65          65   8.1  166.0          1
66          66   6.9   96.0          1
67          67   5.0  118.0          0
68          68   4.0   75.0          0
69          69   8.5  120.0          1
    Unnamed: 0  cgpa     iq  placement
70          70   6.3  127.0          1
71          71   6.1  132.0          1
72          72   7.3  116.0          1
73          73   4.9   61.0          0
74          74   6.7  154.0          1
75          75   4.8  169.0          0
76          76   4.9  155.0          0
77          77   7.3   50.0          1
78          78   6.1   81.0          0
79          79   6.5   90.0          1
    Unnamed: 0  cgpa     iq  placement
80          80   4.9  196.0          0
81          81   5.4  107.0          0
82          82   6.5   37.0          1
83          83   7.5  130.0          1
84          84   5.7  169.0          0
85          85   5.8  166.0          1
86          86   5.1  128.0          0
87          87   5.7  132.0          1
88          88   4.4  149.0          0
89          89   4.9  151.0          0
    Unnamed: 0  cgpa     iq  placement
90          90   7.3   86.0          1
91          91   7.5  158.0          1
92          92   5.2  110.0          0
93          93   6.8  112.0          1
94          94   4.7   52.0          0
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1